### ISSUE TITLE
json with cmc id and slug

### ISSUE THREAD

**Issue by cbellucci** [coinwink/cryptocurrency-logos#1]
Great job! I'm just dealing with this issue at this time and I found the following json: https://files.coinmarketcap.com/generated/search/quick_search.json, has the cmc id and the slug to get the images. You can use it to simplify this process.

**Comment by giekaton** [comment]
Oh yes, this is even better. This would take much less processing resources. Thanks for the tip, I will update the solution.

**Comment by giekaton** [comment]
The repository is now updated with the new solution that uses API discovered by cbellucci.
