### ISSUE TITLE
Please add stablecoins

### ISSUE THREAD

**Issue by dandv** [coinwink/cryptocurrency-logos#4]
* [x] [Gemini USD](https://gemini.com/dollar/) - https://coinmarketcap.com/currencies/gemini-dollar/
* [x] Paxos
* [x] USDC

**Comment by giekaton** [comment]
Hi, check my new project, with Gemini USD here: https://cryptoclothing.cc/crypto-logos/gemini-dollar

USDC: https://cryptoclothing.cc/crypto-logos/usd-coin
Paxos: https://cryptoclothing.cc/crypto-logos/paxos-standard-token
